apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170418476
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170418476
    app.kubernetes.io/part-of: test-app-170418476
  name: java-quarkus-170418476
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170418476
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170418476
    spec:
      containers:
      - image: quay.io/hacdev/ot1vwue8-tenant/test-app-170418476/java-quarkus-170418476@sha256:3d31be3c4f245e2b92c48f46eb2a675e3dde68a411467d638ebbecc42b361e43
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
